# makefile for compiling mraw2tiff.cpp
# This file compiles the c++ codes
# called by and including mraw2tiff.cpp
# and also links them with the C TIFF library libtiff.

# Matthew N. Giarra
# Virginia Tech
# Department of Mechanical Engineering
# matthew.giarra@gmail.com
# 19 March 2015

# This is the name of the executable file that
# will be generated by compiling mraw2tiff.cpp
PROGRAM = mraw2tiff

# This is the name of the symbolic link to the
# c++ compiler that will compile mraw2tiff.cpp
CC = g++

# This is the extension of on the file from
# which the executable will be compiled. 
# This should probably always be cpp.
EXT = cpp

# These are the compiler flags to link the C TIFF library libtiff.
# You may need to change this depending on your system configuration.
CFLAGS = -I/usr/local/Cellar/libtiff/4.0.3/include -L/usr/local/Cellar/libtiff/4.0.3/lib -ltiff

# Type "make" or "make all" to compile the code.
all:
	$(CC) $(CFLAGS) $(PROGRAM).$(EXT) -o $(PROGRAM)
	
# Type "make clean" to delete files
# generated during compiling, including
# the compiled executable.
clean:
	@rm -f $(PROGRAM)
	@rm -rf *dSYM
